### ISSUE TITLE
master file contents.rst not found during build of docs

### ISSUE THREAD

**Issue by rmast** [internetarchive/archive-pdf-tools#36]
I had to apply this [instruction of Hrvoje](https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found) to get the docs building running the apt installed Sphinx v1.8.5:

**Comment by mara004** [comment]
Apparently the root docs file was called `contents.rst` in older versions of Sphinx. As the stackoverflow page suggests, adding `master_doc = 'index'` to `conf.py` should fix the issue, or you could just update Sphinx to a more recent version using pip. `4.3.2` is the latest release, so `1.8.5` is really outdated.

**Comment by rmast** [comment]
So that package is missing from requirements.txt.

**Comment by MerlijnWajer** [comment]
I don't think `sphinx` is necessarily a runtime dependency, but it is required for building the docs. I think the read the docs build of the pdf repo doesn't contain much currently anyway, so I'll try to look into fixing that.

**Comment by mara004** [comment]
Some projects use the `extras_require` option of setuptools for this, e. g. pikepdf: https://github.com/pikepdf/pikepdf/blob/63b660b68b52a0f99ced3015fe4acb66fb6ca8d5/setup.cfg#L53

**Comment by MerlijnWajer** [comment]
Thanks. Would you be up for making a pull request for this change?

**Comment by mara004** [comment]
Yeah, I could look into making a pull request, but it might take some time because I currently have a lot of things to do... 
In general, maybe it would make sense to migrate configuration from `setup.py` to `setup.cfg` where reasonable?

Another thing that surprised me is that you currently require exact versions of dependencies, rather than using `>=` or `~=`, which causes warnings whenever I install/update PIL or PyMuPDF:
```
archive-pdf-tools 1.4.9 requires Pillow==8.3.2, but you have pillow 9.0.0 which is incompatible.
archive-pdf-tools 1.4.9 requires PyMuPDF==1.19.2, but you have pymupdf 1.19.5 which is incompatible.
```

**Comment by mara004** [comment]
I've taken the time and submitted a PR: #38

**Comment by MerlijnWajer** [comment]
Thank you for doing that, merged. :-)
